export default {
  LOGIN: 'LOGIN',
  SET_LOGIN_USER: "SET_LOGIN_USER",
  MARK_NOT_LOGGED_IN_YET: "MARK_NOT_LOGGED_IN_YET",
  GET_LOGIN_USER: "GET_LOGIN_USER",
  LOGOUT: "LOGOUT",
  CLEAR_LOGIN_USER: "CLEAR_LOGIN_USER"
}
