export default {
  SWITCH_SPRINT: 'SWITCH_SPRINT',
  CHANGE_SORT_ORDER: 'CHANGE_SORT_ORDER',
  SET_SORT_ORDER: 'SET_SORT_ORDER',
  CHANGE_TASK_STATUS: 'CHANGE_TASK_STATUS',
  SET_TASK_STATUS: 'SET_TASK_STATUS',
  UPDATE_STORY: 'UPDATE_STORY',
  SET_UPDATED_STORY: 'SET_UPDATED_STORY',
  ADD_TASKS: 'ADD_TASKS',
  SET_ADDED_TASKS: 'SET_ADDED_TASKS',
  UPDATE_TASK: 'UPDATE_TASK',
  SET_UPDATED_TASK: 'SET_UPDATED_TASK',
  DELETE_TASK: 'DELETE_TASK',
  DELETE_TASK_FROM_STATE: 'DELETE_TASK_FROM_STATE'
}
